In [53]:
import pandas as pd
import yfinance as yf
import matplotlib.pyplot as plt
import datetime as dt
import numpy as np

In [54]:
ticker1 = "TSLA"

start1 = dt.date(2010, 1, 1)
end1  = dt.date(2011, 1, 1)

ticker1_data = yf.download(ticker1, start = start1, end = end1)
ticker1_data

[*********************100%%**********************]  1 of 1 completed

                Open      High       Low     Close  Adj Close     Volume
Date
2010-06-29  1.266667  1.666667  1.169333  1.592667   1.592667  281494500
2010-06-30  1.719333  2.028000  1.553333  1.588667   1.588667  257806500
2010-07-01  1.666667  1.728000  1.351333  1.464000   1.464000  123282000
2010-07-02  1.533333  1.540000  1.247333  1.280000   1.280000   77097000
2010-07-06  1.333333  1.333333  1.055333  1.074000   1.074000  103003500
...              ...       ...       ...       ...        ...        ...
2010-12-27  1.868000  1.905333  1.670667  1.703333   1.703333  139528500
2010-12-28  1.723333  1.783333  1.666667  1.760667   1.760667   60844500
2010-12-29  1.802000  1.867333  1.766667  1.848667   1.848667   49788000
2010-12-30  1.846667  1.860000  1.758667  1.766667   1.766667   30616500
2010-12-31  1.771333  1.816667  1.766667  1.775333   1.775333   21268500

[130 rows x 6 columns]

In [55]:
# 

average = 0
SMA1 = 0
# Access the 'High' and 'Low' for each index (date) and perform an operation
for date, row in ticker1_data.iterrows():
    high = row['High']
    low = row['Low']
    # Here you can perform any mathematical operation you want with high and low
    # For example, finding the average (mean) price of the day
    mean_price = (high + low) / 2
    average = average + mean_price
num_columns = len(ticker1_data.columns)
SMA1 = average / num_columns 
print(SMA1)

33.74461091558138

In [56]:
ticker1 = "TSLA"
start1 = dt.date(2010, 1, 1)
end1 = dt.date(2020, 1, 1)

# Download stock data
ticker1_data = yf.download(ticker1, start=start1, end=end1)

# Calculate moving averages
fast_window = 50
slow_window = 200
ticker1_data['Fast_MA'] = ticker1_data['Close'].rolling(window=fast_window).mean()
ticker1_data['Slow_MA'] = ticker1_data['Close'].rolling(window=slow_window).mean()

# Detect crossovers
crossovers = pd.DataFrame(index=ticker1_data.index)
crossovers['Price'] = ticker1_data['Close']
crossovers['Fast_MA'] = ticker1_data['Fast_MA']
crossovers['Slow_MA'] = ticker1_data['Slow_MA']
crossovers['Signal'] = 0.0
crossovers['Signal'] = np.where(crossovers['Fast_MA'] > crossovers['Slow_MA'], 1.0, 0.0)

# Find crossover points
crossovers['Position'] = crossovers['Signal'].diff()

# Show the dates of the crossovers
print(crossovers.loc[crossovers['Position'] == 1])  # Bullish crossovers
print(crossovers.loc[crossovers['Position'] == -1])  # Bearish crossovers

[*********************100%%**********************]  1 of 1 completed
                Price    Fast_MA    Slow_MA  Signal  Position
Date
2011-04-12   1.643333   1.597293   1.581757     1.0       1.0
2011-11-03   2.164000   1.740320   1.732907     1.0       1.0
2012-12-20   2.295333   2.088880   2.083043     1.0       1.0
2015-06-09  17.066668  15.228973  15.178837     1.0       1.0
2016-05-02  16.120001  15.161107  15.099217     1.0       1.0
2016-07-21  14.700000  14.435893  14.434857     1.0       1.0
2017-01-31  16.795334  14.283027  14.280353     1.0       1.0
2018-08-02  23.302668  21.260587  21.173040     1.0       1.0
2018-12-03  23.899332  20.840360  20.797647     1.0       1.0
2019-11-05  21.148001  16.928507  16.859137     1.0       1.0
                Price    Fast_MA    Slow_MA  Signal  Position
Date
2011-08-26   1.582000   1.787427   1.788893     0.0      -1.0
2012-07-06   2.066000   2.057800   2.059010     0.0      -1.0
2015-01-12  13.480667  15.262813  15.305087     0.0      -1.0
2015-11-16  14.287333  15.512107  15.542197     0.0      -1.0
2016-07-07  14.396000  14.502093  14.530880     0.0      -1.0
2016-10-05  13.897333  14.294307  14.314223     0.0      -1.0
2017-12-12  22.735332  21.707373  21.721550     0.0      -1.0
2018-09-11  18.629333  21.130960  21.168867     0.0      -1.0
2019-02-28  21.325333  21.057427  21.090610     0.0      -1.0